### ISSUE TITLE
Suddenly  crash with warning from _UIQueuingScrollView

### ISSUE THREAD

**Issue by Evilcome** [dymx101/DYMRollingBanner#3]
Hi, I'm using this framework in my project, it works nice until I found the below issue:

```
*** Assertion failure in -[_UIQueuingScrollView _didScrollWithAnimation:force:], /SourceCache/UIKit/UIKit-2372/_UIQueuingScrollView.m:778
```

I search the google with same problem here: http://stackoverflow.com/questions/12916422/assertion-failure-in-uiqueuingscrollview-didscrollwithanimationforce

Can u help me check if the problem is really from `DYMRollingBanner` or not. Thanks.

**Comment by dymx101** [comment]
Never had this issue on my own device...but maybe this is a problem of the UIPageViewController itself when it's in the `UIPageViewControllerTransitionStyleScroll` mode, unsure....   

Anyways, I'll keep an eye on this issue but it's also welcomed if you give a pull request to fix it :+1:

**Comment by Evilcome** [comment]
I'd like to, however, I am a newer of objective-c, if swift is accepted maybe I can try. :)

**Comment by dymx101** [comment]
Sorry for stop updating this code for a long time.

@Evilcome You can try objective-c, it's similar with swift.
