### ISSUE TITLE
can I use other web image fetcher?

### ISSUE THREAD

**Issue by Evilcome** [dymx101/DYMRollingBanner#4]
I prefer using the [Kingfisher](https://github.com/onevcat/Kingfisher) as remote image cache, can I config that? Thanks.

**Comment by dymx101** [comment]
It's not possible before but in the latest version (v2.1.5), you can customize the image fetching using the way you prefer by implementing the `setRemoteImageLoadingBlock :` method of the `DYMRollingBannerVC`, and do whatever you like in the block.

**Comment by Evilcome** [comment]
good news. thanks man.

**Comment by Evilcome** [comment]
works well. :+1:
