### ISSUE TITLE
The minimum deployment target 

### ISSUE THREAD

**Issue by yeahdongcn** [dymx101/DYMRollingBanner#5]
I notice that the minimum deployment target is set to iOS 8.0, is there any iOS 8.0 api called?

s.platform     = :ios, '8.0'

**Comment by dymx101** [comment]
Hi, 
This is just a recommended not a mandatory setting....No APIs >= 8.0 has been used in the code, so feel free to downgrade it to '7.0' if you prefer to support iOS 7.0.

**Comment by yeahdongcn** [comment]
https://github.com/dymx101/DYMRollingBanner/pull/6

**Comment by dymx101** [comment]
Thanks to @yeahdongcn, the minimum deployment target has already been set to 7.0, and the spec has already been pushed to pods.

**Comment by dymx101** [comment]
And I think this issue can be closed now.
